#!/bin/sh

rm -rf /run/postgresql && mkdir -p /run/postgresql
rm -rf /tmp/.s*
ln -s /root/.mix $HOME/ 2>/dev/null
ln -s /root/.mix $PWD/ 2>/dev/null

mkdir -p $PGDATA
pg_ctl initdb -D $PGDATA -U $(whoami)
pg_ctl start -D $PGDATA -s -w -t $PGSTARTTIMEOUT
createdb $(whoami)

cat <<EOP | psql
CREATE USER torrent WITH PASSWORD 'CHANGE_ME';
CREATE DATABASE torrent OWNER torrent;
ALTER USER torrent CREATEDB;
\q
EOP

exec mix phoenix.server
